apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: finance-cont
          image: yogeshtc/finance-image-task
          ports:
            - containerPort: 80
